#docker compose yaml file version
version: '3'

#define the services
services:
  # #define the service name
# # betting api zone 
   bettingapizone:
     image: betting 
    # network_mode: host
     ports:
       - "9090:8080"
     volumes:
       - .:/usr/local/tomcat/resources
    networks:
      - ic  
    restart: always
networks:
 ic:
   driver: bridge






